CREATE TABLE IF NOT EXISTS netology.CUSTOMERS
(
    id           integer generated by default as identity,
    name         varchar(200) not null,
    surname      varchar(200) not null,
    age          integer      not null,
    phone_number varchar(15)  not null,
    constraint CUSTOMERS_pk
        primary key (id)
);

CREATE TABLE IF NOT EXISTS netology.ORDERS
(
    id           int generated by default as identity,
    date         date            not null,
    product_name varchar(200)    not null,
    amount       integer         not null,
    customer_id  integer         not null,
    constraint ORDERS_pk
        primary key (id),
    constraint ORDERS_CUSTOMERS_id_fk
        foreign key (customer_id) references netology.CUSTOMERS (id)
);


INSERT INTO netology.CUSTOMERS(name, surname, age, phone_number)
VALUES ('Olga', 'Sidorova', 38, '3443434'),
       ('Ivan', 'Ivanov', 17, '1111111'),
       ('Alexey', 'Petrov', 48, '2222222'),
       ('Anna', 'Perova', 15, '5645656'),
       ('Pavel', 'Smirnov', 38, '554748'),
       ('Alexey', 'Kovrov', 78, '2362527');

insert into netology.orders(date, customer_id, product_name, amount)
VALUES ('240820', 3, 'apple', 100),
       ('240819', 1, 'bread', 50),
       ('240819', 5, 'milk', 90),
       ('240818', 4, 'strawberries', 500),
       ('240820', 6, 'cheese', 450),
       ('240820', 5, 'ice cream', 100);

